### ISSUE TITLE
Error messages - but shape of my api might be wrong?

### ISSUE THREAD

**Issue by BigWillie** [mspiderv/vuejwtauth#1]
I am able to hit my API with postman, and with plain Axios.

I wired vuejwtauth up - I'm using (albeit for the first time) Quasar. I used the sample code 'as is' - copied and pasted straight from your examples. I receive an error message of `Something went wrong`

Poking around in `/drivers/http/axios.js` I can see that sendRequest is working - and my API is returning response.data...... Indeed, I get the following error:

```
TypeError: Cannot read property 'data' of undefined
    at Object.mapLoginResponseToToken (methods.js?efa9:76)
    at async Store.attemptLogin (actions.js?73cf:92)
```

So I am assuming that my api needs to return data in the correct shape for the plugin?

My api returns the following: 

```
config: {adapter: ƒ, transformRequest: {…}, transformResponse: {…}, timeout: 0, xsrfCookieName: "XSRF-TOKEN", …}

data: {
authToken: "..."
refreshToken: ..."
__proto__: Object
}
...

status: 200
statusText: ""

```

What shape of data should my auth return deliver for this to work?

Thanks,
Rob

**Comment by mspiderv** [comment]
Hello Rob,

you have 2 problems in your server response.

1. In every server response you need to send `status: 'success'` (see https://github.com/mspiderv/vuejwtauth/blob/master/src/drivers/http/axios.js#L25). Otherwise, the response will be considered as failed.
2. You need to send your token in `token` property, not in `authToken`. Or, the second solution is to override `mapLoginResponseToToken` function.

Function `mapLoginResponseToToken` is responsible for extracting the token from the server response object. The default implementation is `return response.data.token` which means, the default expected shape of the server response is an JSON object with access token stored in `token` variable. You can override this function (and any other function defined in `methods.js`) in your JWT  options object. Example:

```
new VueJwtAuth({
  Vue,
  store,
  router,
  options: {
    methods: {
      mapLoginResponseToToken (response) {
        return response.data.token
      }
    }
  }
}
```

 Expected JSON response is something like this:

```json
{
   "status":"success", // required
   "token":"blahblah...", // required
   "token_type":"bearer" // optional
}
```

PS: Please let me know, if you are using PHP / Laravel backend. If you do, I can share my backend implementation for you.

Thanks for using my library. If you have any further questions or ideas how to improve this library, please feel free to write me :)

**Comment by BigWillie** [comment]
Thanks. I'm using Hapi in this instance - with Quasar. I shall implement these changes :)

**Comment by BigWillie** [comment]
Would you be open to a pull request? I'd like to refactor https://github.com/mspiderv/vuejwtauth/blob/master/src/drivers/http/axios.js#L25 slightly to also accept a status code in the > 200 < 300 range (as axios hangs the status off the response object)

```
  async sendRequest (method, url, data = {}, config = {}) {
    return axios.request({
      method,
      url,
      data,
      baseURL: this.options.apiBaseURL,
      ...config
    })
      .then(response => {

      const statusCode = response.status ? response.status : false

      if (response.data && ( ( statusCode >= 200 && statusCode < 300) || response.data.status === 'success')) {
        return response
      }
      
      throw new Error('API request failed')

      })
  }
```

**Comment by mspiderv** [comment]
Hi Rob,

I have just released version 1.2.2 which allows you to define your own "*response checker*" function. Look at this example:

```javascript
drivers: {
  http: new AxiosHttpDriver({
    apiBaseURL: 'http://127.0.0.1:3000/api/',
    responseChecker (response) {
      return response && response.data && response.data.status === 'success'
    }
  })
}
```

**Comment by mspiderv** [comment]
Btw, if you want to check your API response status code, take a look at this link https://github.com/axios/axios and Ctrl + F for `validateStatus`

**Comment by BigWillie** [comment]
Fantastic - thanks :) so I've hit an interesting issue: in the event that something fails (eg a form post) I'd like to save the data to local storage - so it can be uploaded when the user next logs in. Just figuring out how best to fit this into the refresh failed method

**Comment by mspiderv** [comment]
Hi Rob,

your last question is not related to the original issue so I consider your problem as resolved and Im closing this issue.

Anyway, take a look at [this package](https://www.npmjs.com/package/vuex-persist). Maybe it will help you. Or just google for "*offline vue*".

PS: Please star my repo if you like it and feel free to create another issue in case of any problems.
